apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: tcp-gateway
#  labels:
#    key: value
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 31500
      name: tcp2
      protocol: GRPC
    hosts:
      - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tcp
spec:
  hosts:
  - "*"
  gateways:
  - tcp-gateway
  http:
  - route:
      - destination:
          host: tcp
          port:
            number: 8081
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: tcp
spec:
  host: tcp
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpHeaderName: "train"
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2
